from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
import time
import json

from app.agentos.memory import agent_memory
from app.agentos.observation import audit_registry
from app.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class ROIMetric:
    agent: str
    metric_name: str
    value: float
    previous_value: float
    change: float
    period: str
    timestamp: float = field(default_factory=time.time)


class ROITracker:
    """Tracks measurable business value generated by each agent.

    Metrics per agent:
      - Collections: recovery_rate, dso_days, amount_recovered, reminders_sent
      - Compliance: accuracy_pct, late_fees_avoided, filings_completed
      - Finance: cash_flow_improvement, working_capital_optimized
      - Growth: revenue_growth_pct, retention_rate, upsell_conversion
      - TReDS: working_capital_generated, savings_realized
      - CEO: briefings_delivered, escalations_handled
    """

    AGENT_METRICS = {
        "collections": ["recovery_rate", "dso_days", "amount_recovered", "reminders_sent"],
        "compliance": ["accuracy_pct", "late_fees_avoided", "filings_completed"],
        "finance": ["cash_flow_improvement", "working_capital_optimized"],
        "growth": ["revenue_growth_pct", "retention_rate", "upsell_conversion"],
        "treds": ["working_capital_generated", "savings_realized"],
        "ceo": ["briefings_delivered", "escalations_handled", "conflicts_resolved"],
    }

    def __init__(self):
        self._metrics: Dict[str, List[ROIMetric]] = {}

    def record_metric(self, agent: str, metric_name: str,
                       value: float, previous_value: float = 0,
                       period: str = "daily"):
        change = value - previous_value
        metric = ROIMetric(
            agent=agent, metric_name=metric_name,
            value=value, previous_value=previous_value,
            change=change, period=period,
        )
        if agent not in self._metrics:
            self._metrics[agent] = []
        self._metrics[agent].append(metric)
        if len(self._metrics[agent]) > 200:
            self._metrics[agent] = self._metrics[agent][-200:]
        agent_memory.store_long_term(agent, f"roi:{metric_name}:{metric.timestamp}", metric.__dict__)

    def get_agent_roi(self, agent: str) -> Dict[str, Any]:
        metrics = self._metrics.get(agent, [])
        if not metrics:
            return {"agent": agent, "metrics": {}, "total_value": 0}
        latest: Dict[str, Any] = {}
        cumulative_metrics = {"amount_recovered", "late_fees_avoided",
                              "working_capital_generated", "savings_realized",
                              "working_capital_optimized"}
        total_value = 0.0
        for m in metrics:
            if m.metric_name not in latest or m.timestamp > latest[m.metric_name]["timestamp"]:
                latest[m.metric_name] = {
                    "value": m.value,
                    "change": m.change,
                    "period": m.period,
                    "timestamp": m.timestamp,
                }
        for metric_name, metric_data in latest.items():
            if metric_name in cumulative_metrics:
                total_value += metric_data["value"]
        return {
            "agent": agent,
            "metrics": latest,
            "total_value_generated": round(total_value, 2),
        }

    def get_all_roi(self) -> Dict[str, Any]:
        agents = list(self._metrics.keys())
        agent_rois = {a: self.get_agent_roi(a) for a in agents}
        total_value = sum(
            r["total_value_generated"] for r in agent_rois.values()
        )
        return {
            "agents": agent_rois,
            "total_agents": len(agents),
            "total_value_generated": round(total_value, 2),
            "tracked_metrics": self.AGENT_METRICS,
        }

    def get_agent_metrics_history(self, agent: str, metric_name: str,
                                   limit: int = 30) -> List[Dict[str, Any]]:
        metrics = [m for m in self._metrics.get(agent, []) if m.metric_name == metric_name]
        return [m.__dict__ for m in metrics[-limit:]]

    def auto_collect_from_observation(self):
        """Pull success/failure data from observation registry for ROI calculation."""
        system = audit_registry.get_system_summary()
        for agent_name, summary in system.get("agent_summaries", {}).items():
            rate = summary.get("success_rate", 0)
            self.record_metric(agent_name, "accuracy_pct", rate, period="lifetime")
        logger.info("roi_collected_from_observation",
                    agents=list(system.get("agent_summaries", {}).keys()))


roi_tracker = ROITracker()
