"""
Schemas for heartbeat cycles, activity events, and autonomous agent results.
"""
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field
from datetime import datetime
from enum import Enum


class ActivityType(str, Enum):
    AGENT_CYCLE = "agent_cycle"
    ALERT = "alert"
    TASK_COMPLETED = "task_completed"
    ERROR = "error"
    MORNING_BRIEFING = "morning_briefing"
    EVENING_SUMMARY = "evening_summary"
    HEARTBEAT = "heartbeat"
    COLLECTIONS_REMINDER = "collections_reminder"
    TREDS_DISCOUNT = "treds_discount"
    GROWTH_INSIGHT = "growth_insight"
    COMPLIANCE_DEADLINE = "compliance_deadline"


class Priority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ActivityEvent(BaseModel):
    """Single activity event for the live dashboard stream"""
    id: str = Field(default_factory=lambda: f"evt_{datetime.utcnow().timestamp():.0f}")
    type: ActivityType
    priority: Priority = Priority.MEDIUM
    agent: str
    org_id: str
    title: str
    message: str
    data: Dict[str, Any] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    acknowledged: bool = False


class HeartbeatCycle(BaseModel):
    """Result of a nightly heartbeat cycle"""
    cycle_id: str = Field(default_factory=lambda: f"hb_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}")
    org_id: str
    start_time: datetime = Field(default_factory=datetime.utcnow)
    end_time: Optional[datetime] = None
    agents_run: List[str] = Field(default_factory=list)
    results: Dict[str, Dict[str, Any]] = Field(default_factory=dict)
    alerts_generated: int = 0
    actions_taken: int = 0
    success: bool = True
    error: Optional[str] = None

    @property
    def duration_seconds(self) -> float:
        if self.end_time:
            return (self.end_time - self.start_time).total_seconds()
        return (datetime.utcnow() - self.start_time).total_seconds()


class MorningBriefing(BaseModel):
    """Morning briefing generated by CEO agent"""
    org_id: str
    date: str = Field(default_factory=lambda: datetime.utcnow().strftime("%Y-%m-%d"))
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    summary: str
    cash_position: Dict[str, Any] = Field(default_factory=dict)
    overdue_invoices: List[Dict[str, Any]] = Field(default_factory=list)
    upcoming_deadlines: List[Dict[str, Any]] = Field(default_factory=list)
    collections_priority: List[Dict[str, Any]] = Field(default_factory=list)
    treds_opportunities: List[Dict[str, Any]] = Field(default_factory=list)
    growth_insights: List[Dict[str, Any]] = Field(default_factory=list)
    action_items: List[str] = Field(default_factory=list)


class EveningSummary(BaseModel):
    """End-of-day summary generated by CEO agent"""
    org_id: str
    date: str = Field(default_factory=lambda: datetime.utcnow().strftime("%Y-%m-%d"))
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    summary: str
    tasks_completed: List[str] = Field(default_factory=list)
    revenue_today: float = 0.0
    expenses_today: float = 0.0
    collections_today: float = 0.0
    alerts_resolved: int = 0
    pending_actions: List[str] = Field(default_factory=list)


class AgentHealthStatus(BaseModel):
    """Health status for an autonomous agent"""
    agent_name: str
    last_cycle: Optional[datetime] = None
    cycles_today: int = 0
    success_rate_24h: float = 100.0
    avg_cycle_duration_seconds: float = 0.0
    errors_24h: int = 0
    status: str = "healthy"
