// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moneyops.Empty)
    com.google.protobuf.MessageOrBuilder {
}
