// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

public interface FinancialSummaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moneyops.FinancialSummaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string org_id = 1;</code>
   * @return The orgId.
   */
  java.lang.String getOrgId();
  /**
   * <code>string org_id = 1;</code>
   * @return The bytes for orgId.
   */
  com.google.protobuf.ByteString
      getOrgIdBytes();
}
