// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

/**
 * Protobuf type {@code moneyops.FinanceMetrics}
 */
public final class FinanceMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:moneyops.FinanceMetrics)
    FinanceMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FinanceMetrics.newBuilder() to construct.
  private FinanceMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FinanceMetrics() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FinanceMetrics();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moneyops.grpc.Moneyops.internal_static_moneyops_FinanceMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moneyops.grpc.Moneyops.internal_static_moneyops_FinanceMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moneyops.grpc.FinanceMetrics.class, com.moneyops.grpc.FinanceMetrics.Builder.class);
  }

  public static final int TOTAL_REVENUE_FIELD_NUMBER = 1;
  private double totalRevenue_ = 0D;
  /**
   * <code>double total_revenue = 1;</code>
   * @return The totalRevenue.
   */
  @java.lang.Override
  public double getTotalRevenue() {
    return totalRevenue_;
  }

  public static final int TOTAL_EXPENSES_FIELD_NUMBER = 2;
  private double totalExpenses_ = 0D;
  /**
   * <code>double total_expenses = 2;</code>
   * @return The totalExpenses.
   */
  @java.lang.Override
  public double getTotalExpenses() {
    return totalExpenses_;
  }

  public static final int NET_PROFIT_FIELD_NUMBER = 3;
  private double netProfit_ = 0D;
  /**
   * <code>double net_profit = 3;</code>
   * @return The netProfit.
   */
  @java.lang.Override
  public double getNetProfit() {
    return netProfit_;
  }

  public static final int CASH_BALANCE_FIELD_NUMBER = 4;
  private double cashBalance_ = 0D;
  /**
   * <code>double cash_balance = 4;</code>
   * @return The cashBalance.
   */
  @java.lang.Override
  public double getCashBalance() {
    return cashBalance_;
  }

  public static final int OUTSTANDING_INVOICES_FIELD_NUMBER = 5;
  private int outstandingInvoices_ = 0;
  /**
   * <code>int32 outstanding_invoices = 5;</code>
   * @return The outstandingInvoices.
   */
  @java.lang.Override
  public int getOutstandingInvoices() {
    return outstandingInvoices_;
  }

  public static final int OUTSTANDING_AMOUNT_FIELD_NUMBER = 6;
  private double outstandingAmount_ = 0D;
  /**
   * <code>double outstanding_amount = 6;</code>
   * @return The outstandingAmount.
   */
  @java.lang.Override
  public double getOutstandingAmount() {
    return outstandingAmount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(totalRevenue_) != 0) {
      output.writeDouble(1, totalRevenue_);
    }
    if (java.lang.Double.doubleToRawLongBits(totalExpenses_) != 0) {
      output.writeDouble(2, totalExpenses_);
    }
    if (java.lang.Double.doubleToRawLongBits(netProfit_) != 0) {
      output.writeDouble(3, netProfit_);
    }
    if (java.lang.Double.doubleToRawLongBits(cashBalance_) != 0) {
      output.writeDouble(4, cashBalance_);
    }
    if (outstandingInvoices_ != 0) {
      output.writeInt32(5, outstandingInvoices_);
    }
    if (java.lang.Double.doubleToRawLongBits(outstandingAmount_) != 0) {
      output.writeDouble(6, outstandingAmount_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(totalRevenue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, totalRevenue_);
    }
    if (java.lang.Double.doubleToRawLongBits(totalExpenses_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, totalExpenses_);
    }
    if (java.lang.Double.doubleToRawLongBits(netProfit_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, netProfit_);
    }
    if (java.lang.Double.doubleToRawLongBits(cashBalance_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, cashBalance_);
    }
    if (outstandingInvoices_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, outstandingInvoices_);
    }
    if (java.lang.Double.doubleToRawLongBits(outstandingAmount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, outstandingAmount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moneyops.grpc.FinanceMetrics)) {
      return super.equals(obj);
    }
    com.moneyops.grpc.FinanceMetrics other = (com.moneyops.grpc.FinanceMetrics) obj;

    if (java.lang.Double.doubleToLongBits(getTotalRevenue())
        != java.lang.Double.doubleToLongBits(
            other.getTotalRevenue())) return false;
    if (java.lang.Double.doubleToLongBits(getTotalExpenses())
        != java.lang.Double.doubleToLongBits(
            other.getTotalExpenses())) return false;
    if (java.lang.Double.doubleToLongBits(getNetProfit())
        != java.lang.Double.doubleToLongBits(
            other.getNetProfit())) return false;
    if (java.lang.Double.doubleToLongBits(getCashBalance())
        != java.lang.Double.doubleToLongBits(
            other.getCashBalance())) return false;
    if (getOutstandingInvoices()
        != other.getOutstandingInvoices()) return false;
    if (java.lang.Double.doubleToLongBits(getOutstandingAmount())
        != java.lang.Double.doubleToLongBits(
            other.getOutstandingAmount())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_REVENUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTotalRevenue()));
    hash = (37 * hash) + TOTAL_EXPENSES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTotalExpenses()));
    hash = (37 * hash) + NET_PROFIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNetProfit()));
    hash = (37 * hash) + CASH_BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCashBalance()));
    hash = (37 * hash) + OUTSTANDING_INVOICES_FIELD_NUMBER;
    hash = (53 * hash) + getOutstandingInvoices();
    hash = (37 * hash) + OUTSTANDING_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getOutstandingAmount()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moneyops.grpc.FinanceMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.FinanceMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.FinanceMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.FinanceMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.FinanceMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.FinanceMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.FinanceMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moneyops.grpc.FinanceMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.moneyops.grpc.FinanceMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.moneyops.grpc.FinanceMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moneyops.grpc.FinanceMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moneyops.grpc.FinanceMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moneyops.grpc.FinanceMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code moneyops.FinanceMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:moneyops.FinanceMetrics)
      com.moneyops.grpc.FinanceMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_FinanceMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_FinanceMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moneyops.grpc.FinanceMetrics.class, com.moneyops.grpc.FinanceMetrics.Builder.class);
    }

    // Construct using com.moneyops.grpc.FinanceMetrics.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      totalRevenue_ = 0D;
      totalExpenses_ = 0D;
      netProfit_ = 0D;
      cashBalance_ = 0D;
      outstandingInvoices_ = 0;
      outstandingAmount_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_FinanceMetrics_descriptor;
    }

    @java.lang.Override
    public com.moneyops.grpc.FinanceMetrics getDefaultInstanceForType() {
      return com.moneyops.grpc.FinanceMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public com.moneyops.grpc.FinanceMetrics build() {
      com.moneyops.grpc.FinanceMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moneyops.grpc.FinanceMetrics buildPartial() {
      com.moneyops.grpc.FinanceMetrics result = new com.moneyops.grpc.FinanceMetrics(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.moneyops.grpc.FinanceMetrics result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.totalRevenue_ = totalRevenue_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalExpenses_ = totalExpenses_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.netProfit_ = netProfit_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cashBalance_ = cashBalance_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.outstandingInvoices_ = outstandingInvoices_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.outstandingAmount_ = outstandingAmount_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moneyops.grpc.FinanceMetrics) {
        return mergeFrom((com.moneyops.grpc.FinanceMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moneyops.grpc.FinanceMetrics other) {
      if (other == com.moneyops.grpc.FinanceMetrics.getDefaultInstance()) return this;
      if (other.getTotalRevenue() != 0D) {
        setTotalRevenue(other.getTotalRevenue());
      }
      if (other.getTotalExpenses() != 0D) {
        setTotalExpenses(other.getTotalExpenses());
      }
      if (other.getNetProfit() != 0D) {
        setNetProfit(other.getNetProfit());
      }
      if (other.getCashBalance() != 0D) {
        setCashBalance(other.getCashBalance());
      }
      if (other.getOutstandingInvoices() != 0) {
        setOutstandingInvoices(other.getOutstandingInvoices());
      }
      if (other.getOutstandingAmount() != 0D) {
        setOutstandingAmount(other.getOutstandingAmount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              totalRevenue_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              totalExpenses_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              netProfit_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              cashBalance_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 40: {
              outstandingInvoices_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 49: {
              outstandingAmount_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double totalRevenue_ ;
    /**
     * <code>double total_revenue = 1;</code>
     * @return The totalRevenue.
     */
    @java.lang.Override
    public double getTotalRevenue() {
      return totalRevenue_;
    }
    /**
     * <code>double total_revenue = 1;</code>
     * @param value The totalRevenue to set.
     * @return This builder for chaining.
     */
    public Builder setTotalRevenue(double value) {

      totalRevenue_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double total_revenue = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalRevenue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      totalRevenue_ = 0D;
      onChanged();
      return this;
    }

    private double totalExpenses_ ;
    /**
     * <code>double total_expenses = 2;</code>
     * @return The totalExpenses.
     */
    @java.lang.Override
    public double getTotalExpenses() {
      return totalExpenses_;
    }
    /**
     * <code>double total_expenses = 2;</code>
     * @param value The totalExpenses to set.
     * @return This builder for chaining.
     */
    public Builder setTotalExpenses(double value) {

      totalExpenses_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double total_expenses = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalExpenses() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalExpenses_ = 0D;
      onChanged();
      return this;
    }

    private double netProfit_ ;
    /**
     * <code>double net_profit = 3;</code>
     * @return The netProfit.
     */
    @java.lang.Override
    public double getNetProfit() {
      return netProfit_;
    }
    /**
     * <code>double net_profit = 3;</code>
     * @param value The netProfit to set.
     * @return This builder for chaining.
     */
    public Builder setNetProfit(double value) {

      netProfit_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double net_profit = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetProfit() {
      bitField0_ = (bitField0_ & ~0x00000004);
      netProfit_ = 0D;
      onChanged();
      return this;
    }

    private double cashBalance_ ;
    /**
     * <code>double cash_balance = 4;</code>
     * @return The cashBalance.
     */
    @java.lang.Override
    public double getCashBalance() {
      return cashBalance_;
    }
    /**
     * <code>double cash_balance = 4;</code>
     * @param value The cashBalance to set.
     * @return This builder for chaining.
     */
    public Builder setCashBalance(double value) {

      cashBalance_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double cash_balance = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCashBalance() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cashBalance_ = 0D;
      onChanged();
      return this;
    }

    private int outstandingInvoices_ ;
    /**
     * <code>int32 outstanding_invoices = 5;</code>
     * @return The outstandingInvoices.
     */
    @java.lang.Override
    public int getOutstandingInvoices() {
      return outstandingInvoices_;
    }
    /**
     * <code>int32 outstanding_invoices = 5;</code>
     * @param value The outstandingInvoices to set.
     * @return This builder for chaining.
     */
    public Builder setOutstandingInvoices(int value) {

      outstandingInvoices_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 outstanding_invoices = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutstandingInvoices() {
      bitField0_ = (bitField0_ & ~0x00000010);
      outstandingInvoices_ = 0;
      onChanged();
      return this;
    }

    private double outstandingAmount_ ;
    /**
     * <code>double outstanding_amount = 6;</code>
     * @return The outstandingAmount.
     */
    @java.lang.Override
    public double getOutstandingAmount() {
      return outstandingAmount_;
    }
    /**
     * <code>double outstanding_amount = 6;</code>
     * @param value The outstandingAmount to set.
     * @return This builder for chaining.
     */
    public Builder setOutstandingAmount(double value) {

      outstandingAmount_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double outstanding_amount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutstandingAmount() {
      bitField0_ = (bitField0_ & ~0x00000020);
      outstandingAmount_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:moneyops.FinanceMetrics)
  }

  // @@protoc_insertion_point(class_scope:moneyops.FinanceMetrics)
  private static final com.moneyops.grpc.FinanceMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moneyops.grpc.FinanceMetrics();
  }

  public static com.moneyops.grpc.FinanceMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FinanceMetrics>
      PARSER = new com.google.protobuf.AbstractParser<FinanceMetrics>() {
    @java.lang.Override
    public FinanceMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FinanceMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FinanceMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moneyops.grpc.FinanceMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

