// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

public interface FinanceMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moneyops.FinanceMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double total_revenue = 1;</code>
   * @return The totalRevenue.
   */
  double getTotalRevenue();

  /**
   * <code>double total_expenses = 2;</code>
   * @return The totalExpenses.
   */
  double getTotalExpenses();

  /**
   * <code>double net_profit = 3;</code>
   * @return The netProfit.
   */
  double getNetProfit();

  /**
   * <code>double cash_balance = 4;</code>
   * @return The cashBalance.
   */
  double getCashBalance();

  /**
   * <code>int32 outstanding_invoices = 5;</code>
   * @return The outstandingInvoices.
   */
  int getOutstandingInvoices();

  /**
   * <code>double outstanding_amount = 6;</code>
   * @return The outstandingAmount.
   */
  double getOutstandingAmount();
}
