// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

/**
 * Protobuf type {@code moneyops.GetFinanceMetricsResponse}
 */
public final class GetFinanceMetricsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:moneyops.GetFinanceMetricsResponse)
    GetFinanceMetricsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetFinanceMetricsResponse.newBuilder() to construct.
  private GetFinanceMetricsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetFinanceMetricsResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetFinanceMetricsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetFinanceMetricsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetFinanceMetricsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moneyops.grpc.GetFinanceMetricsResponse.class, com.moneyops.grpc.GetFinanceMetricsResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.moneyops.grpc.FinanceMetrics data_;
  /**
   * <code>.moneyops.FinanceMetrics data = 2;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.moneyops.FinanceMetrics data = 2;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.moneyops.grpc.FinanceMetrics getData() {
    return data_ == null ? com.moneyops.grpc.FinanceMetrics.getDefaultInstance() : data_;
  }
  /**
   * <code>.moneyops.FinanceMetrics data = 2;</code>
   */
  @java.lang.Override
  public com.moneyops.grpc.FinanceMetricsOrBuilder getDataOrBuilder() {
    return data_ == null ? com.moneyops.grpc.FinanceMetrics.getDefaultInstance() : data_;
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  private com.moneyops.grpc.ErrorResponse error_;
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.moneyops.grpc.ErrorResponse getError() {
    return error_ == null ? com.moneyops.grpc.ErrorResponse.getDefaultInstance() : error_;
  }
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   */
  @java.lang.Override
  public com.moneyops.grpc.ErrorResponseOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.moneyops.grpc.ErrorResponse.getDefaultInstance() : error_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getData());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getError());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getData());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getError());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moneyops.grpc.GetFinanceMetricsResponse)) {
      return super.equals(obj);
    }
    com.moneyops.grpc.GetFinanceMetricsResponse other = (com.moneyops.grpc.GetFinanceMetricsResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.moneyops.grpc.GetFinanceMetricsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.moneyops.grpc.GetFinanceMetricsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moneyops.grpc.GetFinanceMetricsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moneyops.grpc.GetFinanceMetricsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code moneyops.GetFinanceMetricsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:moneyops.GetFinanceMetricsResponse)
      com.moneyops.grpc.GetFinanceMetricsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetFinanceMetricsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetFinanceMetricsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moneyops.grpc.GetFinanceMetricsResponse.class, com.moneyops.grpc.GetFinanceMetricsResponse.Builder.class);
    }

    // Construct using com.moneyops.grpc.GetFinanceMetricsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDataFieldBuilder();
        getErrorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetFinanceMetricsResponse_descriptor;
    }

    @java.lang.Override
    public com.moneyops.grpc.GetFinanceMetricsResponse getDefaultInstanceForType() {
      return com.moneyops.grpc.GetFinanceMetricsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.moneyops.grpc.GetFinanceMetricsResponse build() {
      com.moneyops.grpc.GetFinanceMetricsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moneyops.grpc.GetFinanceMetricsResponse buildPartial() {
      com.moneyops.grpc.GetFinanceMetricsResponse result = new com.moneyops.grpc.GetFinanceMetricsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.moneyops.grpc.GetFinanceMetricsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.data_ = dataBuilder_ == null
            ? data_
            : dataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moneyops.grpc.GetFinanceMetricsResponse) {
        return mergeFrom((com.moneyops.grpc.GetFinanceMetricsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moneyops.grpc.GetFinanceMetricsResponse other) {
      if (other == com.moneyops.grpc.GetFinanceMetricsResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private com.moneyops.grpc.FinanceMetrics data_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moneyops.grpc.FinanceMetrics, com.moneyops.grpc.FinanceMetrics.Builder, com.moneyops.grpc.FinanceMetricsOrBuilder> dataBuilder_;
    /**
     * <code>.moneyops.FinanceMetrics data = 2;</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.moneyops.FinanceMetrics data = 2;</code>
     * @return The data.
     */
    public com.moneyops.grpc.FinanceMetrics getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.moneyops.grpc.FinanceMetrics.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.moneyops.FinanceMetrics data = 2;</code>
     */
    public Builder setData(com.moneyops.grpc.FinanceMetrics value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.moneyops.FinanceMetrics data = 2;</code>
     */
    public Builder setData(
        com.moneyops.grpc.FinanceMetrics.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.moneyops.FinanceMetrics data = 2;</code>
     */
    public Builder mergeData(com.moneyops.grpc.FinanceMetrics value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          data_ != null &&
          data_ != com.moneyops.grpc.FinanceMetrics.getDefaultInstance()) {
          getDataBuilder().mergeFrom(value);
        } else {
          data_ = value;
        }
      } else {
        dataBuilder_.mergeFrom(value);
      }
      if (data_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.moneyops.FinanceMetrics data = 2;</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000002);
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.moneyops.FinanceMetrics data = 2;</code>
     */
    public com.moneyops.grpc.FinanceMetrics.Builder getDataBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.moneyops.FinanceMetrics data = 2;</code>
     */
    public com.moneyops.grpc.FinanceMetricsOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.moneyops.grpc.FinanceMetrics.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.moneyops.FinanceMetrics data = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moneyops.grpc.FinanceMetrics, com.moneyops.grpc.FinanceMetrics.Builder, com.moneyops.grpc.FinanceMetricsOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moneyops.grpc.FinanceMetrics, com.moneyops.grpc.FinanceMetrics.Builder, com.moneyops.grpc.FinanceMetricsOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private com.moneyops.grpc.ErrorResponse error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moneyops.grpc.ErrorResponse, com.moneyops.grpc.ErrorResponse.Builder, com.moneyops.grpc.ErrorResponseOrBuilder> errorBuilder_;
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     * @return The error.
     */
    public com.moneyops.grpc.ErrorResponse getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.moneyops.grpc.ErrorResponse.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public Builder setError(com.moneyops.grpc.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public Builder setError(
        com.moneyops.grpc.ErrorResponse.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public Builder mergeError(com.moneyops.grpc.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          error_ != null &&
          error_ != com.moneyops.grpc.ErrorResponse.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      if (error_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000004);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public com.moneyops.grpc.ErrorResponse.Builder getErrorBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public com.moneyops.grpc.ErrorResponseOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.moneyops.grpc.ErrorResponse.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moneyops.grpc.ErrorResponse, com.moneyops.grpc.ErrorResponse.Builder, com.moneyops.grpc.ErrorResponseOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moneyops.grpc.ErrorResponse, com.moneyops.grpc.ErrorResponse.Builder, com.moneyops.grpc.ErrorResponseOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:moneyops.GetFinanceMetricsResponse)
  }

  // @@protoc_insertion_point(class_scope:moneyops.GetFinanceMetricsResponse)
  private static final com.moneyops.grpc.GetFinanceMetricsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moneyops.grpc.GetFinanceMetricsResponse();
  }

  public static com.moneyops.grpc.GetFinanceMetricsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetFinanceMetricsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetFinanceMetricsResponse>() {
    @java.lang.Override
    public GetFinanceMetricsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetFinanceMetricsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetFinanceMetricsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moneyops.grpc.GetFinanceMetricsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

