// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

public interface GetInvoicesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moneyops.GetInvoicesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string org_id = 1;</code>
   * @return The orgId.
   */
  java.lang.String getOrgId();
  /**
   * <code>string org_id = 1;</code>
   * @return The bytes for orgId.
   */
  com.google.protobuf.ByteString
      getOrgIdBytes();

  /**
   * <code>.moneyops.InvoiceStatus status = 2;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.moneyops.InvoiceStatus status = 2;</code>
   * @return The status.
   */
  com.moneyops.grpc.InvoiceStatus getStatus();

  /**
   * <code>int32 limit = 3;</code>
   * @return The limit.
   */
  int getLimit();
}
