// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

public interface GetInvoicesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moneyops.GetInvoicesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  java.util.List<com.moneyops.grpc.Invoice> 
      getInvoicesList();
  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  com.moneyops.grpc.Invoice getInvoices(int index);
  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  int getInvoicesCount();
  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  java.util.List<? extends com.moneyops.grpc.InvoiceOrBuilder> 
      getInvoicesOrBuilderList();
  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  com.moneyops.grpc.InvoiceOrBuilder getInvoicesOrBuilder(
      int index);

  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   * @return The error.
   */
  com.moneyops.grpc.ErrorResponse getError();
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   */
  com.moneyops.grpc.ErrorResponseOrBuilder getErrorOrBuilder();
}
