// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

/**
 * Protobuf type {@code moneyops.GetInvoicesResponse}
 */
public final class GetInvoicesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:moneyops.GetInvoicesResponse)
    GetInvoicesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetInvoicesResponse.newBuilder() to construct.
  private GetInvoicesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetInvoicesResponse() {
    invoices_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetInvoicesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetInvoicesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetInvoicesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moneyops.grpc.GetInvoicesResponse.class, com.moneyops.grpc.GetInvoicesResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_ = false;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int INVOICES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.moneyops.grpc.Invoice> invoices_;
  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.moneyops.grpc.Invoice> getInvoicesList() {
    return invoices_;
  }
  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.moneyops.grpc.InvoiceOrBuilder> 
      getInvoicesOrBuilderList() {
    return invoices_;
  }
  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  @java.lang.Override
  public int getInvoicesCount() {
    return invoices_.size();
  }
  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  @java.lang.Override
  public com.moneyops.grpc.Invoice getInvoices(int index) {
    return invoices_.get(index);
  }
  /**
   * <code>repeated .moneyops.Invoice invoices = 2;</code>
   */
  @java.lang.Override
  public com.moneyops.grpc.InvoiceOrBuilder getInvoicesOrBuilder(
      int index) {
    return invoices_.get(index);
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  private com.moneyops.grpc.ErrorResponse error_;
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   * @return Whether the error field is set.
   */
  @java.lang.Override
  public boolean hasError() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   * @return The error.
   */
  @java.lang.Override
  public com.moneyops.grpc.ErrorResponse getError() {
    return error_ == null ? com.moneyops.grpc.ErrorResponse.getDefaultInstance() : error_;
  }
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   */
  @java.lang.Override
  public com.moneyops.grpc.ErrorResponseOrBuilder getErrorOrBuilder() {
    return error_ == null ? com.moneyops.grpc.ErrorResponse.getDefaultInstance() : error_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    for (int i = 0; i < invoices_.size(); i++) {
      output.writeMessage(2, invoices_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getError());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    for (int i = 0; i < invoices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, invoices_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getError());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moneyops.grpc.GetInvoicesResponse)) {
      return super.equals(obj);
    }
    com.moneyops.grpc.GetInvoicesResponse other = (com.moneyops.grpc.GetInvoicesResponse) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getInvoicesList()
        .equals(other.getInvoicesList())) return false;
    if (hasError() != other.hasError()) return false;
    if (hasError()) {
      if (!getError()
          .equals(other.getError())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    if (getInvoicesCount() > 0) {
      hash = (37 * hash) + INVOICES_FIELD_NUMBER;
      hash = (53 * hash) + getInvoicesList().hashCode();
    }
    if (hasError()) {
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.moneyops.grpc.GetInvoicesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.moneyops.grpc.GetInvoicesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moneyops.grpc.GetInvoicesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moneyops.grpc.GetInvoicesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code moneyops.GetInvoicesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:moneyops.GetInvoicesResponse)
      com.moneyops.grpc.GetInvoicesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetInvoicesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetInvoicesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moneyops.grpc.GetInvoicesResponse.class, com.moneyops.grpc.GetInvoicesResponse.Builder.class);
    }

    // Construct using com.moneyops.grpc.GetInvoicesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInvoicesFieldBuilder();
        getErrorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      success_ = false;
      if (invoicesBuilder_ == null) {
        invoices_ = java.util.Collections.emptyList();
      } else {
        invoices_ = null;
        invoicesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_GetInvoicesResponse_descriptor;
    }

    @java.lang.Override
    public com.moneyops.grpc.GetInvoicesResponse getDefaultInstanceForType() {
      return com.moneyops.grpc.GetInvoicesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.moneyops.grpc.GetInvoicesResponse build() {
      com.moneyops.grpc.GetInvoicesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moneyops.grpc.GetInvoicesResponse buildPartial() {
      com.moneyops.grpc.GetInvoicesResponse result = new com.moneyops.grpc.GetInvoicesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.moneyops.grpc.GetInvoicesResponse result) {
      if (invoicesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          invoices_ = java.util.Collections.unmodifiableList(invoices_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.invoices_ = invoices_;
      } else {
        result.invoices_ = invoicesBuilder_.build();
      }
    }

    private void buildPartial0(com.moneyops.grpc.GetInvoicesResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.success_ = success_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.error_ = errorBuilder_ == null
            ? error_
            : errorBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moneyops.grpc.GetInvoicesResponse) {
        return mergeFrom((com.moneyops.grpc.GetInvoicesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moneyops.grpc.GetInvoicesResponse other) {
      if (other == com.moneyops.grpc.GetInvoicesResponse.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (invoicesBuilder_ == null) {
        if (!other.invoices_.isEmpty()) {
          if (invoices_.isEmpty()) {
            invoices_ = other.invoices_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureInvoicesIsMutable();
            invoices_.addAll(other.invoices_);
          }
          onChanged();
        }
      } else {
        if (!other.invoices_.isEmpty()) {
          if (invoicesBuilder_.isEmpty()) {
            invoicesBuilder_.dispose();
            invoicesBuilder_ = null;
            invoices_ = other.invoices_;
            bitField0_ = (bitField0_ & ~0x00000002);
            invoicesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInvoicesFieldBuilder() : null;
          } else {
            invoicesBuilder_.addAllMessages(other.invoices_);
          }
        }
      }
      if (other.hasError()) {
        mergeError(other.getError());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              success_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.moneyops.grpc.Invoice m =
                  input.readMessage(
                      com.moneyops.grpc.Invoice.parser(),
                      extensionRegistry);
              if (invoicesBuilder_ == null) {
                ensureInvoicesIsMutable();
                invoices_.add(m);
              } else {
                invoicesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getErrorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.moneyops.grpc.Invoice> invoices_ =
      java.util.Collections.emptyList();
    private void ensureInvoicesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        invoices_ = new java.util.ArrayList<com.moneyops.grpc.Invoice>(invoices_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.moneyops.grpc.Invoice, com.moneyops.grpc.Invoice.Builder, com.moneyops.grpc.InvoiceOrBuilder> invoicesBuilder_;

    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public java.util.List<com.moneyops.grpc.Invoice> getInvoicesList() {
      if (invoicesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invoices_);
      } else {
        return invoicesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public int getInvoicesCount() {
      if (invoicesBuilder_ == null) {
        return invoices_.size();
      } else {
        return invoicesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public com.moneyops.grpc.Invoice getInvoices(int index) {
      if (invoicesBuilder_ == null) {
        return invoices_.get(index);
      } else {
        return invoicesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public Builder setInvoices(
        int index, com.moneyops.grpc.Invoice value) {
      if (invoicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicesIsMutable();
        invoices_.set(index, value);
        onChanged();
      } else {
        invoicesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public Builder setInvoices(
        int index, com.moneyops.grpc.Invoice.Builder builderForValue) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.set(index, builderForValue.build());
        onChanged();
      } else {
        invoicesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public Builder addInvoices(com.moneyops.grpc.Invoice value) {
      if (invoicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicesIsMutable();
        invoices_.add(value);
        onChanged();
      } else {
        invoicesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public Builder addInvoices(
        int index, com.moneyops.grpc.Invoice value) {
      if (invoicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicesIsMutable();
        invoices_.add(index, value);
        onChanged();
      } else {
        invoicesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public Builder addInvoices(
        com.moneyops.grpc.Invoice.Builder builderForValue) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.add(builderForValue.build());
        onChanged();
      } else {
        invoicesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public Builder addInvoices(
        int index, com.moneyops.grpc.Invoice.Builder builderForValue) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.add(index, builderForValue.build());
        onChanged();
      } else {
        invoicesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public Builder addAllInvoices(
        java.lang.Iterable<? extends com.moneyops.grpc.Invoice> values) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invoices_);
        onChanged();
      } else {
        invoicesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public Builder clearInvoices() {
      if (invoicesBuilder_ == null) {
        invoices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        invoicesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public Builder removeInvoices(int index) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.remove(index);
        onChanged();
      } else {
        invoicesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public com.moneyops.grpc.Invoice.Builder getInvoicesBuilder(
        int index) {
      return getInvoicesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public com.moneyops.grpc.InvoiceOrBuilder getInvoicesOrBuilder(
        int index) {
      if (invoicesBuilder_ == null) {
        return invoices_.get(index);  } else {
        return invoicesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public java.util.List<? extends com.moneyops.grpc.InvoiceOrBuilder> 
         getInvoicesOrBuilderList() {
      if (invoicesBuilder_ != null) {
        return invoicesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invoices_);
      }
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public com.moneyops.grpc.Invoice.Builder addInvoicesBuilder() {
      return getInvoicesFieldBuilder().addBuilder(
          com.moneyops.grpc.Invoice.getDefaultInstance());
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public com.moneyops.grpc.Invoice.Builder addInvoicesBuilder(
        int index) {
      return getInvoicesFieldBuilder().addBuilder(
          index, com.moneyops.grpc.Invoice.getDefaultInstance());
    }
    /**
     * <code>repeated .moneyops.Invoice invoices = 2;</code>
     */
    public java.util.List<com.moneyops.grpc.Invoice.Builder> 
         getInvoicesBuilderList() {
      return getInvoicesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.moneyops.grpc.Invoice, com.moneyops.grpc.Invoice.Builder, com.moneyops.grpc.InvoiceOrBuilder> 
        getInvoicesFieldBuilder() {
      if (invoicesBuilder_ == null) {
        invoicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.moneyops.grpc.Invoice, com.moneyops.grpc.Invoice.Builder, com.moneyops.grpc.InvoiceOrBuilder>(
                invoices_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        invoices_ = null;
      }
      return invoicesBuilder_;
    }

    private com.moneyops.grpc.ErrorResponse error_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moneyops.grpc.ErrorResponse, com.moneyops.grpc.ErrorResponse.Builder, com.moneyops.grpc.ErrorResponseOrBuilder> errorBuilder_;
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     * @return The error.
     */
    public com.moneyops.grpc.ErrorResponse getError() {
      if (errorBuilder_ == null) {
        return error_ == null ? com.moneyops.grpc.ErrorResponse.getDefaultInstance() : error_;
      } else {
        return errorBuilder_.getMessage();
      }
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public Builder setError(com.moneyops.grpc.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        error_ = value;
      } else {
        errorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public Builder setError(
        com.moneyops.grpc.ErrorResponse.Builder builderForValue) {
      if (errorBuilder_ == null) {
        error_ = builderForValue.build();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public Builder mergeError(com.moneyops.grpc.ErrorResponse value) {
      if (errorBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          error_ != null &&
          error_ != com.moneyops.grpc.ErrorResponse.getDefaultInstance()) {
          getErrorBuilder().mergeFrom(value);
        } else {
          error_ = value;
        }
      } else {
        errorBuilder_.mergeFrom(value);
      }
      if (error_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public Builder clearError() {
      bitField0_ = (bitField0_ & ~0x00000004);
      error_ = null;
      if (errorBuilder_ != null) {
        errorBuilder_.dispose();
        errorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public com.moneyops.grpc.ErrorResponse.Builder getErrorBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    public com.moneyops.grpc.ErrorResponseOrBuilder getErrorOrBuilder() {
      if (errorBuilder_ != null) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        return error_ == null ?
            com.moneyops.grpc.ErrorResponse.getDefaultInstance() : error_;
      }
    }
    /**
     * <code>.moneyops.ErrorResponse error = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.moneyops.grpc.ErrorResponse, com.moneyops.grpc.ErrorResponse.Builder, com.moneyops.grpc.ErrorResponseOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.moneyops.grpc.ErrorResponse, com.moneyops.grpc.ErrorResponse.Builder, com.moneyops.grpc.ErrorResponseOrBuilder>(
                getError(),
                getParentForChildren(),
                isClean());
        error_ = null;
      }
      return errorBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:moneyops.GetInvoicesResponse)
  }

  // @@protoc_insertion_point(class_scope:moneyops.GetInvoicesResponse)
  private static final com.moneyops.grpc.GetInvoicesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moneyops.grpc.GetInvoicesResponse();
  }

  public static com.moneyops.grpc.GetInvoicesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetInvoicesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetInvoicesResponse>() {
    @java.lang.Override
    public GetInvoicesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetInvoicesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetInvoicesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moneyops.grpc.GetInvoicesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

