// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

public interface GetOnboardingStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moneyops.GetOnboardingStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>.moneyops.OnboardingStatus data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.moneyops.OnboardingStatus data = 2;</code>
   * @return The data.
   */
  com.moneyops.grpc.OnboardingStatus getData();
  /**
   * <code>.moneyops.OnboardingStatus data = 2;</code>
   */
  com.moneyops.grpc.OnboardingStatusOrBuilder getDataOrBuilder();

  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   * @return The error.
   */
  com.moneyops.grpc.ErrorResponse getError();
  /**
   * <code>.moneyops.ErrorResponse error = 3;</code>
   */
  com.moneyops.grpc.ErrorResponseOrBuilder getErrorOrBuilder();
}
