// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

/**
 * Protobuf enum {@code moneyops.InvoiceStatus}
 */
public enum InvoiceStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>INVOICE_STATUS_UNSPECIFIED = 0;</code>
   */
  INVOICE_STATUS_UNSPECIFIED(0),
  /**
   * <code>DRAFT = 1;</code>
   */
  DRAFT(1),
  /**
   * <code>SENT = 2;</code>
   */
  SENT(2),
  /**
   * <code>OVERDUE = 3;</code>
   */
  OVERDUE(3),
  /**
   * <code>PAID = 4;</code>
   */
  PAID(4),
  /**
   * <code>CANCELLED = 5;</code>
   */
  CANCELLED(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>INVOICE_STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int INVOICE_STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <code>DRAFT = 1;</code>
   */
  public static final int DRAFT_VALUE = 1;
  /**
   * <code>SENT = 2;</code>
   */
  public static final int SENT_VALUE = 2;
  /**
   * <code>OVERDUE = 3;</code>
   */
  public static final int OVERDUE_VALUE = 3;
  /**
   * <code>PAID = 4;</code>
   */
  public static final int PAID_VALUE = 4;
  /**
   * <code>CANCELLED = 5;</code>
   */
  public static final int CANCELLED_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static InvoiceStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static InvoiceStatus forNumber(int value) {
    switch (value) {
      case 0: return INVOICE_STATUS_UNSPECIFIED;
      case 1: return DRAFT;
      case 2: return SENT;
      case 3: return OVERDUE;
      case 4: return PAID;
      case 5: return CANCELLED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<InvoiceStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      InvoiceStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<InvoiceStatus>() {
          public InvoiceStatus findValueByNumber(int number) {
            return InvoiceStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.moneyops.grpc.Moneyops.getDescriptor().getEnumTypes().get(0);
  }

  private static final InvoiceStatus[] VALUES = values();

  public static InvoiceStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private InvoiceStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:moneyops.InvoiceStatus)
}

