// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

public interface OnboardingStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moneyops.OnboardingStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool onboarding_complete = 1;</code>
   * @return The onboardingComplete.
   */
  boolean getOnboardingComplete();

  /**
   * <code>string org_id = 2;</code>
   * @return The orgId.
   */
  java.lang.String getOrgId();
  /**
   * <code>string org_id = 2;</code>
   * @return The bytes for orgId.
   */
  com.google.protobuf.ByteString
      getOrgIdBytes();

  /**
   * <code>string org_uuid = 3;</code>
   * @return The orgUuid.
   */
  java.lang.String getOrgUuid();
  /**
   * <code>string org_uuid = 3;</code>
   * @return The bytes for orgUuid.
   */
  com.google.protobuf.ByteString
      getOrgUuidBytes();

  /**
   * <code>string organization_id = 4;</code>
   * @return The organizationId.
   */
  java.lang.String getOrganizationId();
  /**
   * <code>string organization_id = 4;</code>
   * @return The bytes for organizationId.
   */
  com.google.protobuf.ByteString
      getOrganizationIdBytes();
}
