// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

public interface PaginationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:moneyops.PaginationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 limit = 2;</code>
   * @return The limit.
   */
  int getLimit();
}
