// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: moneyops.proto

// Protobuf Java Version: 3.25.3
package com.moneyops.grpc;

/**
 * Protobuf type {@code moneyops.SendCollectionEmailRequest}
 */
public final class SendCollectionEmailRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:moneyops.SendCollectionEmailRequest)
    SendCollectionEmailRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SendCollectionEmailRequest.newBuilder() to construct.
  private SendCollectionEmailRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SendCollectionEmailRequest() {
    invoiceId_ = "";
    clientEmail_ = "";
    clientName_ = "";
    invoiceNumber_ = "";
    dueDate_ = "";
    orgId_ = "";
    tone_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SendCollectionEmailRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.moneyops.grpc.Moneyops.internal_static_moneyops_SendCollectionEmailRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.moneyops.grpc.Moneyops.internal_static_moneyops_SendCollectionEmailRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.moneyops.grpc.SendCollectionEmailRequest.class, com.moneyops.grpc.SendCollectionEmailRequest.Builder.class);
  }

  public static final int INVOICE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object invoiceId_ = "";
  /**
   * <code>string invoice_id = 1;</code>
   * @return The invoiceId.
   */
  @java.lang.Override
  public java.lang.String getInvoiceId() {
    java.lang.Object ref = invoiceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      invoiceId_ = s;
      return s;
    }
  }
  /**
   * <code>string invoice_id = 1;</code>
   * @return The bytes for invoiceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInvoiceIdBytes() {
    java.lang.Object ref = invoiceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      invoiceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_EMAIL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientEmail_ = "";
  /**
   * <code>string client_email = 2;</code>
   * @return The clientEmail.
   */
  @java.lang.Override
  public java.lang.String getClientEmail() {
    java.lang.Object ref = clientEmail_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientEmail_ = s;
      return s;
    }
  }
  /**
   * <code>string client_email = 2;</code>
   * @return The bytes for clientEmail.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientEmailBytes() {
    java.lang.Object ref = clientEmail_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientEmail_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENT_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientName_ = "";
  /**
   * <code>string client_name = 3;</code>
   * @return The clientName.
   */
  @java.lang.Override
  public java.lang.String getClientName() {
    java.lang.Object ref = clientName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientName_ = s;
      return s;
    }
  }
  /**
   * <code>string client_name = 3;</code>
   * @return The bytes for clientName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientNameBytes() {
    java.lang.Object ref = clientName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INVOICE_NUMBER_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object invoiceNumber_ = "";
  /**
   * <code>string invoice_number = 4;</code>
   * @return The invoiceNumber.
   */
  @java.lang.Override
  public java.lang.String getInvoiceNumber() {
    java.lang.Object ref = invoiceNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      invoiceNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string invoice_number = 4;</code>
   * @return The bytes for invoiceNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInvoiceNumberBytes() {
    java.lang.Object ref = invoiceNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      invoiceNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 5;
  private double amount_ = 0D;
  /**
   * <code>double amount = 5;</code>
   * @return The amount.
   */
  @java.lang.Override
  public double getAmount() {
    return amount_;
  }

  public static final int DUE_DATE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dueDate_ = "";
  /**
   * <code>string due_date = 6;</code>
   * @return The dueDate.
   */
  @java.lang.Override
  public java.lang.String getDueDate() {
    java.lang.Object ref = dueDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dueDate_ = s;
      return s;
    }
  }
  /**
   * <code>string due_date = 6;</code>
   * @return The bytes for dueDate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDueDateBytes() {
    java.lang.Object ref = dueDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dueDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORG_ID_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object orgId_ = "";
  /**
   * <code>string org_id = 7;</code>
   * @return The orgId.
   */
  @java.lang.Override
  public java.lang.String getOrgId() {
    java.lang.Object ref = orgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      orgId_ = s;
      return s;
    }
  }
  /**
   * <code>string org_id = 7;</code>
   * @return The bytes for orgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrgIdBytes() {
    java.lang.Object ref = orgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      orgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TONE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tone_ = "";
  /**
   * <code>string tone = 8;</code>
   * @return The tone.
   */
  @java.lang.Override
  public java.lang.String getTone() {
    java.lang.Object ref = tone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tone_ = s;
      return s;
    }
  }
  /**
   * <code>string tone = 8;</code>
   * @return The bytes for tone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToneBytes() {
    java.lang.Object ref = tone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(invoiceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, invoiceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientEmail_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(invoiceNumber_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, invoiceNumber_);
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      output.writeDouble(5, amount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dueDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dueDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orgId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, orgId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tone_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tone_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(invoiceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, invoiceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientEmail_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientEmail_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(invoiceNumber_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, invoiceNumber_);
    }
    if (java.lang.Double.doubleToRawLongBits(amount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, amount_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dueDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dueDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orgId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, orgId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tone_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tone_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.moneyops.grpc.SendCollectionEmailRequest)) {
      return super.equals(obj);
    }
    com.moneyops.grpc.SendCollectionEmailRequest other = (com.moneyops.grpc.SendCollectionEmailRequest) obj;

    if (!getInvoiceId()
        .equals(other.getInvoiceId())) return false;
    if (!getClientEmail()
        .equals(other.getClientEmail())) return false;
    if (!getClientName()
        .equals(other.getClientName())) return false;
    if (!getInvoiceNumber()
        .equals(other.getInvoiceNumber())) return false;
    if (java.lang.Double.doubleToLongBits(getAmount())
        != java.lang.Double.doubleToLongBits(
            other.getAmount())) return false;
    if (!getDueDate()
        .equals(other.getDueDate())) return false;
    if (!getOrgId()
        .equals(other.getOrgId())) return false;
    if (!getTone()
        .equals(other.getTone())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INVOICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getInvoiceId().hashCode();
    hash = (37 * hash) + CLIENT_EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getClientEmail().hashCode();
    hash = (37 * hash) + CLIENT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getClientName().hashCode();
    hash = (37 * hash) + INVOICE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getInvoiceNumber().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    hash = (37 * hash) + DUE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDueDate().hashCode();
    hash = (37 * hash) + ORG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOrgId().hashCode();
    hash = (37 * hash) + TONE_FIELD_NUMBER;
    hash = (53 * hash) + getTone().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.moneyops.grpc.SendCollectionEmailRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.moneyops.grpc.SendCollectionEmailRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.moneyops.grpc.SendCollectionEmailRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.moneyops.grpc.SendCollectionEmailRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code moneyops.SendCollectionEmailRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:moneyops.SendCollectionEmailRequest)
      com.moneyops.grpc.SendCollectionEmailRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_SendCollectionEmailRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_SendCollectionEmailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moneyops.grpc.SendCollectionEmailRequest.class, com.moneyops.grpc.SendCollectionEmailRequest.Builder.class);
    }

    // Construct using com.moneyops.grpc.SendCollectionEmailRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      invoiceId_ = "";
      clientEmail_ = "";
      clientName_ = "";
      invoiceNumber_ = "";
      amount_ = 0D;
      dueDate_ = "";
      orgId_ = "";
      tone_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.moneyops.grpc.Moneyops.internal_static_moneyops_SendCollectionEmailRequest_descriptor;
    }

    @java.lang.Override
    public com.moneyops.grpc.SendCollectionEmailRequest getDefaultInstanceForType() {
      return com.moneyops.grpc.SendCollectionEmailRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.moneyops.grpc.SendCollectionEmailRequest build() {
      com.moneyops.grpc.SendCollectionEmailRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.moneyops.grpc.SendCollectionEmailRequest buildPartial() {
      com.moneyops.grpc.SendCollectionEmailRequest result = new com.moneyops.grpc.SendCollectionEmailRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.moneyops.grpc.SendCollectionEmailRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.invoiceId_ = invoiceId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.clientEmail_ = clientEmail_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.clientName_ = clientName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.invoiceNumber_ = invoiceNumber_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.amount_ = amount_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.dueDate_ = dueDate_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.orgId_ = orgId_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.tone_ = tone_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.moneyops.grpc.SendCollectionEmailRequest) {
        return mergeFrom((com.moneyops.grpc.SendCollectionEmailRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.moneyops.grpc.SendCollectionEmailRequest other) {
      if (other == com.moneyops.grpc.SendCollectionEmailRequest.getDefaultInstance()) return this;
      if (!other.getInvoiceId().isEmpty()) {
        invoiceId_ = other.invoiceId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getClientEmail().isEmpty()) {
        clientEmail_ = other.clientEmail_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getClientName().isEmpty()) {
        clientName_ = other.clientName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getInvoiceNumber().isEmpty()) {
        invoiceNumber_ = other.invoiceNumber_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      if (!other.getDueDate().isEmpty()) {
        dueDate_ = other.dueDate_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getOrgId().isEmpty()) {
        orgId_ = other.orgId_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getTone().isEmpty()) {
        tone_ = other.tone_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              invoiceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              clientEmail_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              clientName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              invoiceNumber_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 41: {
              amount_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 50: {
              dueDate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              orgId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              tone_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object invoiceId_ = "";
    /**
     * <code>string invoice_id = 1;</code>
     * @return The invoiceId.
     */
    public java.lang.String getInvoiceId() {
      java.lang.Object ref = invoiceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        invoiceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string invoice_id = 1;</code>
     * @return The bytes for invoiceId.
     */
    public com.google.protobuf.ByteString
        getInvoiceIdBytes() {
      java.lang.Object ref = invoiceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        invoiceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string invoice_id = 1;</code>
     * @param value The invoiceId to set.
     * @return This builder for chaining.
     */
    public Builder setInvoiceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      invoiceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string invoice_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvoiceId() {
      invoiceId_ = getDefaultInstance().getInvoiceId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string invoice_id = 1;</code>
     * @param value The bytes for invoiceId to set.
     * @return This builder for chaining.
     */
    public Builder setInvoiceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      invoiceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object clientEmail_ = "";
    /**
     * <code>string client_email = 2;</code>
     * @return The clientEmail.
     */
    public java.lang.String getClientEmail() {
      java.lang.Object ref = clientEmail_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientEmail_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_email = 2;</code>
     * @return The bytes for clientEmail.
     */
    public com.google.protobuf.ByteString
        getClientEmailBytes() {
      java.lang.Object ref = clientEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_email = 2;</code>
     * @param value The clientEmail to set.
     * @return This builder for chaining.
     */
    public Builder setClientEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientEmail_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string client_email = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientEmail() {
      clientEmail_ = getDefaultInstance().getClientEmail();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string client_email = 2;</code>
     * @param value The bytes for clientEmail to set.
     * @return This builder for chaining.
     */
    public Builder setClientEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientEmail_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object clientName_ = "";
    /**
     * <code>string client_name = 3;</code>
     * @return The clientName.
     */
    public java.lang.String getClientName() {
      java.lang.Object ref = clientName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_name = 3;</code>
     * @return The bytes for clientName.
     */
    public com.google.protobuf.ByteString
        getClientNameBytes() {
      java.lang.Object ref = clientName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_name = 3;</code>
     * @param value The clientName to set.
     * @return This builder for chaining.
     */
    public Builder setClientName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string client_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientName() {
      clientName_ = getDefaultInstance().getClientName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string client_name = 3;</code>
     * @param value The bytes for clientName to set.
     * @return This builder for chaining.
     */
    public Builder setClientNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object invoiceNumber_ = "";
    /**
     * <code>string invoice_number = 4;</code>
     * @return The invoiceNumber.
     */
    public java.lang.String getInvoiceNumber() {
      java.lang.Object ref = invoiceNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        invoiceNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string invoice_number = 4;</code>
     * @return The bytes for invoiceNumber.
     */
    public com.google.protobuf.ByteString
        getInvoiceNumberBytes() {
      java.lang.Object ref = invoiceNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        invoiceNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string invoice_number = 4;</code>
     * @param value The invoiceNumber to set.
     * @return This builder for chaining.
     */
    public Builder setInvoiceNumber(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      invoiceNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string invoice_number = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvoiceNumber() {
      invoiceNumber_ = getDefaultInstance().getInvoiceNumber();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string invoice_number = 4;</code>
     * @param value The bytes for invoiceNumber to set.
     * @return This builder for chaining.
     */
    public Builder setInvoiceNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      invoiceNumber_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private double amount_ ;
    /**
     * <code>double amount = 5;</code>
     * @return The amount.
     */
    @java.lang.Override
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 5;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(double value) {

      amount_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double amount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      bitField0_ = (bitField0_ & ~0x00000010);
      amount_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object dueDate_ = "";
    /**
     * <code>string due_date = 6;</code>
     * @return The dueDate.
     */
    public java.lang.String getDueDate() {
      java.lang.Object ref = dueDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dueDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string due_date = 6;</code>
     * @return The bytes for dueDate.
     */
    public com.google.protobuf.ByteString
        getDueDateBytes() {
      java.lang.Object ref = dueDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dueDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string due_date = 6;</code>
     * @param value The dueDate to set.
     * @return This builder for chaining.
     */
    public Builder setDueDate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dueDate_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string due_date = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDueDate() {
      dueDate_ = getDefaultInstance().getDueDate();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string due_date = 6;</code>
     * @param value The bytes for dueDate to set.
     * @return This builder for chaining.
     */
    public Builder setDueDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dueDate_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object orgId_ = "";
    /**
     * <code>string org_id = 7;</code>
     * @return The orgId.
     */
    public java.lang.String getOrgId() {
      java.lang.Object ref = orgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string org_id = 7;</code>
     * @return The bytes for orgId.
     */
    public com.google.protobuf.ByteString
        getOrgIdBytes() {
      java.lang.Object ref = orgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string org_id = 7;</code>
     * @param value The orgId to set.
     * @return This builder for chaining.
     */
    public Builder setOrgId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      orgId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string org_id = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrgId() {
      orgId_ = getDefaultInstance().getOrgId();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string org_id = 7;</code>
     * @param value The bytes for orgId to set.
     * @return This builder for chaining.
     */
    public Builder setOrgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orgId_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object tone_ = "";
    /**
     * <code>string tone = 8;</code>
     * @return The tone.
     */
    public java.lang.String getTone() {
      java.lang.Object ref = tone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tone = 8;</code>
     * @return The bytes for tone.
     */
    public com.google.protobuf.ByteString
        getToneBytes() {
      java.lang.Object ref = tone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tone = 8;</code>
     * @param value The tone to set.
     * @return This builder for chaining.
     */
    public Builder setTone(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tone_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string tone = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTone() {
      tone_ = getDefaultInstance().getTone();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string tone = 8;</code>
     * @param value The bytes for tone to set.
     * @return This builder for chaining.
     */
    public Builder setToneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tone_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:moneyops.SendCollectionEmailRequest)
  }

  // @@protoc_insertion_point(class_scope:moneyops.SendCollectionEmailRequest)
  private static final com.moneyops.grpc.SendCollectionEmailRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.moneyops.grpc.SendCollectionEmailRequest();
  }

  public static com.moneyops.grpc.SendCollectionEmailRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendCollectionEmailRequest>
      PARSER = new com.google.protobuf.AbstractParser<SendCollectionEmailRequest>() {
    @java.lang.Override
    public SendCollectionEmailRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SendCollectionEmailRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendCollectionEmailRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.moneyops.grpc.SendCollectionEmailRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

